version: '3.4'

services:
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  web:
    build: ./petstagram
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./petstagram/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./petstagram/envs/.env
    depends_on:
      - postgres
      - mailcatcher
  postgres:    
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1123QwER
      POSTGRES_USER: postgres
      POSTGRES_DB: petstagram_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
