version: '3.4'

services:
  web:
    build: ./petstagram
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./petstagram/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./petstagram/.env.dev
    depends_on:
      - postgres
  postgres:    
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1123QwER
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data
