# Generated by Django 4.2.2 on 2023-06-06 16:45

from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="location",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="pet_image",
            field=models.ImageField(
                upload_to="",
                validators=[petstagram.photos.validators.image_size_validator_5mb],
            ),
        ),
    ]
