# Generated by Django 4.2.2 on 2023-07-05 15:31

import django.core.validators
from django.db import migrations, models
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10), petstagram.photos.validators.text_underscore_validator]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pet_image',
            field=models.ImageField(upload_to='photos', validators=[petstagram.photos.validators.image_size_validator_5mb]),
        ),
    ]
