# Generated by Django 4.1.1 on 2022-11-21 18:01

import cloudinary.models
from django.db import migrations
import petstagram.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, validators=[petstagram.photos.validators.validate_file_less_than_5mb]),
        ),
    ]
