# Generated by Django 4.2.2 on 2023-07-05 17:55

from django.db import migrations, models
import petstagram.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_petstagramuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='petstagramuser',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('do not show', 'DO_NOT_SHOW')], default=petstagram.accounts.models.Gender['DO_NOT_SHOW'], max_length=11),
        ),
    ]
