# Generated by Django 4.2.2 on 2023-07-19 17:26

from django.db import migrations, models
import petstagram.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_gender2_alter_petstagramuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petstagramuser',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('do not show', 'DO_NOT_SHOW')], default=petstagram.accounts.models.Gender['DO_NOT_SHOW'], max_length=12),
        ),
    ]
