# Generated by Django 4.2.2 on 2023-06-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_alter_photo_pet_image"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "to_photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="photos.photo"
                    ),
                ),
            ],
        ),
    ]
