# Generated by Django 4.2.9 on 2024-02-05 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0005_alter_petphoto_photo"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photocomment",
            name="pet_photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="photos.petphoto"
            ),
        ),
        migrations.AlterField(
            model_name="photolike",
            name="pet_photo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="photos.petphoto"
            ),
        ),
    ]
