# Generated by Django 4.2.9 on 2024-01-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
