# Generated by Django 4.2.9 on 2024-03-07 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pets", "0004_pet_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
